### ISSUE TITLE
method for name updating missed

### ISSUE THREAD

**Issue by tallinn-learning** [PDarija/6_homework#2]
https://github.com/PDarija/6_homework/blob/62f557324b63e2008163ed95a701a9225e8d27ea/src/main/java/org/example/User.java#L19

**Comment by PDarija** [comment]
added if/ else constructor. Please take a look

**Comment by tallinn-learning** [comment]
So, you have created method but don't pass a parameter. Please provide parameter and update using this.

**Comment by PDarija** [comment]
I made some changes. Please check
